apiVersion: apps/v1
kind: Deployment
metadata:
  name: gittest-deployment
  labels:
    app: gittest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gittest
  template:
    metadata:
      labels:
        app: gittest
    spec:
      containers:
      - name: git-test
        image: git-test:v1
        volumeMounts:
        - mountPath: /cyp
          name: cyp-volume
        ports:
        - containerPort: 80
      volumes:
      - name: cyp-volume
        persistentVolumeClaim:
          claimName: myclaim
