apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0
spec:
  capacity: 
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data
