apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: mydnn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydnn
  template:
    metadata:
      labels:
        app: mydnn
    spec:
      containers:
      - name: my-test
        image: my-test:v0
        command: ["python"]
        args: ["run_train.py"]
        volumeMounts:
        - mountPath: /data
          name: my-volume
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: my-volume
        hostPath:
          path: /home/chenyiping/data-3/
          type: Directory
