apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloth-deployment
  labels:
    app: clothdnn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clothdnn
  template:
    metadata:
      labels:
        app: clothdnn
    spec:
      containers:
      - name: cloth-test
        image: cloth-test:v0
        command: ["python"]
        args: ["run_train.py"]
        volumeMounts:
        - mountPath: /data
          name: cloth-volume
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: cloth-volume
        nfs:
          server: 10.0.10.203
          path: /data
