apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  labels:
    app: mydnn
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: mydnn
    spec:
      restartPolicy: Never
      containers:
      - name: my-test
        image: my-test:v1
        command: ["python"]
        args: ["run_train.py"]
        volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /usr/src/cloth-dnn-test
          name: script-volume
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: data-volume
        nfs:
          server: 10.0.*.*
          path: /data
      - name: script-volume
        hostPath:
          path: /script/dir
