apiVersion: batch/v1
kind: Job
metadata:
  name: cloth-job-1
  labels:
    app: clothdnn
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: clothdnn
    spec:
      restartPolicy: Never
      containers:
      - name: cloth-test
        image: cloth-test:v1
        command: ["python"]
        args: ["run_train.py"]
        volumeMounts:
        - mountPath: /data
          name: cloth-volume
        - mountPath: /usr/src/cloth-dnn-test
          name: script-volume
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: cloth-volume
        nfs:
          server: 10.0.10.203
          path: /data
      - name: script-volume
        hostPath:
          path: /home/chenyiping/Workspace/Gitlab/cloth_dnn
